version: '3'
services:
  blaze-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      TRUST_PROXY: 1
    ports:
      - 3030:3030

  blaze-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 80:80
    depends_on:
      - blaze-server
    volumes:
      - ./nginx/compose-nginx.conf:/etc/nginx/nginx.conf
